//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCardApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashCardApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ➕ Добавить карточку.
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить карточку.
        /// </summary>
        internal static string AddCardDialog_Title {
            get {
                return ResourceManager.GetString("AddCardDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавьте карточки или выберите другую тему.
        /// </summary>
        internal static string AddCardsOrSelectTopic {
            get {
                return ResourceManager.GetString("AddCardsOrSelectTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ *.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОТВЕТ.
        /// </summary>
        internal static string AnswerHeader {
            get {
                return ResourceManager.GetString("AnswerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ:.
        /// </summary>
        internal static string AnswerLabel {
            get {
                return ResourceManager.GetString("AnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите для показа ответа.
        /// </summary>
        internal static string ClickToShowAnswer {
            get {
                return ResourceManager.GetString("ClickToShowAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Не знаю.
        /// </summary>
        internal static string DontKnow {
            get {
                return ResourceManager.GetString("DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать карточку.
        /// </summary>
        internal static string EditCardDialog_Title {
            get {
                return ResourceManager.GetString("EditCardDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Знаю.
        /// </summary>
        internal static string Know {
            get {
                return ResourceManager.GetString("Know", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знаю.
        /// </summary>
        internal static string Known {
            get {
                return ResourceManager.GetString("Known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ ЗНАЮ.
        /// </summary>
        internal static string KnownCards {
            get {
                return ResourceManager.GetString("KnownCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изучаю.
        /// </summary>
        internal static string Learning {
            get {
                return ResourceManager.GetString("Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 ИЗУЧАЮ.
        /// </summary>
        internal static string LearningCards {
            get {
                return ResourceManager.GetString("LearningCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashCard App - Изучение с карточками.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🆕 НОВЫЕ.
        /// </summary>
        internal static string NewCards {
            get {
                return ResourceManager.GetString("NewCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая тема.
        /// </summary>
        internal static string NewTopic {
            get {
                return ResourceManager.GetString("NewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующая ⏭️.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет карточек для изучения.
        /// </summary>
        internal static string NoCardsToStudy {
            get {
                return ResourceManager.GetString("NoCardsToStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или создать новую →.
        /// </summary>
        internal static string OrCreateNew {
            get {
                return ResourceManager.GetString("OrCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный просмотр.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏮️ Предыдущая.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос *.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВОПРОС.
        /// </summary>
        internal static string QuestionHeader {
            get {
                return ResourceManager.GetString("QuestionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос:.
        /// </summary>
        internal static string QuestionLabel {
            get {
                return ResourceManager.GetString("QuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцените свои знания.
        /// </summary>
        internal static string RateKnowledge {
            get {
                return ResourceManager.GetString("RateKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Обновить.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Начать сначала.
        /// </summary>
        internal static string RestartStudy {
            get {
                return ResourceManager.GetString("RestartStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👁️ Показать ответ.
        /// </summary>
        internal static string ShowAnswer {
            get {
                return ResourceManager.GetString("ShowAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус:.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📚 Режим обучения.
        /// </summary>
        internal static string StudyMode {
            get {
                return ResourceManager.GetString("StudyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📚 Режим обучения.
        /// </summary>
        internal static string StudyModeHeader {
            get {
                return ResourceManager.GetString("StudyModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим обучения.
        /// </summary>
        internal static string StudyModeWindow_Title {
            get {
                return ResourceManager.GetString("StudyModeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема:.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема: {0}.
        /// </summary>
        internal static string TopicFormat {
            get {
                return ResourceManager.GetString("TopicFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема: {0}.
        /// </summary>
        internal static string TopicLabel {
            get {
                return ResourceManager.GetString("TopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема *.
        /// </summary>
        internal static string TopicRequired {
            get {
                return ResourceManager.GetString("TopicRequired", resourceCulture);
            }
        }
    }
} 